@host = http://localhost:5218

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Sasuke",
    "lastName": "Uchiha",
    "email": "sasuke@gmail.com",
    "password": "uchiha"
}