@host = http://localhost:5218

POST {{host}}/dinners/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNGQxNTIyMC00MTNjLTQzYmUtYmY4OS04ZDQ2NTc2NGI2OTkiLCJnaXZlbl9uYW1lIjoiU2FzdWtlIiwiZmFtaWx5X25hbWUiOiJVY2hpaGEiLCJqdGkiOiJmMjUyNDBiOC0zMjJlLTRkOTItOTRhYS1mYTI1YWM5NzU1YTAiLCJleHAiOjE2NzY3NjEwMTUsImlzcyI6IkRpbmVEZWNrIiwiYXVkIjoiRGluZURlY2sifQ.ZtrKnVAlQGkgQcfkfgGaARMiQ_2ewmA85IqXMRjG0vE